[package]
name = "vbo"
version = "0.1.0"
edition = "2021"
description = "Parse and write VBOX Automotive file formats"

[dependencies]
log = "0.4"
time = { version = "0.3", features = ["formatting"] }
dms-coordinates = "0.1"
